# This workflow will wrap gpdconfig as a zipapp binary

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Zipapp
      run: |
        python -m pip install -t gpdconfig/wincontrols hid
        python -m zipapp -p "/usr/bin/env python3" gpdconfig
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: gpdconfig
        path: gpdconfig.pyz
